# Generated by Django 4.2 on 2023-06-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('data_rozpoczecia', models.DateField()),
                ('ilosc_miejsc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Uczestnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazyapp.kurs')),
            ],
        ),
    ]
